export const products = [
    {
        id: 5,
        link: '/products/shikhakhai-powder',
        img: '/assets/Assets/shikakipowder/Shikakai  Powder  Frontn.png',
        title: 'Pure Shikakai Powder   Promote Hair Growth and Scalp Health Naturally',
        description: 'Shikakai Powder is a natural hair cleanser that strengthens roots, promotes growth, and adds shine while gently nourishing your scalp and hair',
        updateInfo: 'Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/organic-shikakai-powder?_pos=10&_sid=5edfdd030&_ss=r',
        route: '/recipe-aloe-vera',
        price: "$7",
        categories: ['Hair'],
    },
    {
        id: 1, price: "$27.99",
        link: '/products/shilajit',
        img: '/assets/Assets/Shilajit/shilajitqq.png',
        title: 'Premium Shilajit Resin | 100% Pure & Organic | Natural Energy & Stamina Booster (50g) ',
        description: ' Boost your energy and vitality with pure Shilajit. A 100% natural supplement for stamina, endurance, and overall wellness. ',
        updateInfo: ' Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/premium-shilajit-resin-100-pure-organic-natural-energy-stamina-booster-50g',
        // route: '/products/sandalwood-powder',
        categories: ['Wellness'],
    },
    {
        id: 2, price: "$21.99",
        link: '/products/yuvprash',
        img: 'assets/Assets/Yuvprash/yuvprash.png',
        title: 'Yuvprash Tablets by Exotic Veda – 100% Herbal Supplement for Immunity & Overall Wellness ',
        description: ' Boost your immunity and vitality with Yuvprash Tablets. A natural herbal supplement inspired by Vedic Chyawanprash for wellness.',
        updateInfo: ' Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/exotic-veda-yuvprash-tablets-vedic-chyawanprash-in-tablet-form-herbal-supplement',
        // route: '/products/sandalwood-powder',
        categories: ['Wellness'],
    },

    {
        id: 1,
        link: '/products/aloevera-powder',
        img: '/assets/Assets/Aloe/Aloe vera  front.png',
        title: 'Pure Aloe Vera Powder  : Your Natural Solution for Skin and Hair Care',
        description: 'Refresh your skin and hair with our pure Aloe Vera Powder, known for its cooling and moisturizing benefits. Ideal for face masks and hair care!',
        updateInfo: ' Click here to Learn Our  Tips  ',
        buyLink: 'https://www.revaais.shop/products/pure-aloe-vera-powder?_pos=1&_sid=200c3bfb5&_ss=r?variant=48956960702785',
        route: '/products/aloevera-powder',
        price: "$7",
        categories: ['Hair', 'Skin', 'Diet'],
    },

    {
        id: 2,
        link: '/products/amla-powder',
        img: '/assets/Assets/Amla/Amla Powderfront.png', title: 'Amla Powder: Natural Solution for Healthy Hair, Skin & Diet',
        description: 'Boost your skin and hair care with pure Amla Powder, rich in Vitamin C. Ideal for enhancing natural radiance and promoting healthy hair growth',
        updateInfo: 'Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/organic-amla-powder-herbal-supplement-indian-gooseberry-or-emblica-officinalis-helps-detoxify-boost-immunity-hair-growth-long-hairs-promotes-eye-health-100-natural-non-gmo-100g?_pos=1&_sid=5edfdd030&_ss=r',
        route: '/products/amla-powder',
        price: "$7.99",
        categories: ['Hair', 'Skin', 'Diet'],
    },
    {
        id: 3,
        link: '/products/curry-leaf-powder',
        img: '/assets/Assets/curryleaf/Curry Front.png',
        title: 'Curry Leaf Powder   Strengthen Roots and Reduce Hair Loss Naturally',
        description: 'Boost your hair health with our natural Curry Leaf Powder. It helps reduce hair fall, promotes growth, and adds shine to your hair.',
        updateInfo: 'Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/exotic-veda-curry-powder-organic-curry-powder?_pos=3&_sid=5edfdd030&_ss=r',
        route: '/products/curry-leaf-powder',
        price: "$5.34",
        categories: ['Hair', 'Skin', 'Diet'],
    },
    {
        id: 4,
        link: '/products/henna-powder',
        img: '/assets/Assets/hennapowder/Henna Powder .png',
        title: 'Pure Henna Powder   Nourish, Strengthen, and Color Your Hair Naturally',
        description: 'Enhance your hair’s health and color with our pure Henna Powder. It provides a natural tint, conditions hair, and promotes a healthy scalp',
        updateInfo: 'Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/exotic-veda-organic-henna-powder-100-natural-hair-dye-from-rajasthan-india-lawsonia-inermis-non-gmo-deep-brown-100g?_pos=11&_sid=5edfdd030&_ss=r',
        route: '/products/henna-powder',
        price: "$6.99",
        categories: ['Hair',],
    },
    {
        id: 6,
        link: '/products/multani-mitti',
        img: '/assets/Assets/multani/MultaniMirtti.png',
        title: 'Pure Multani Mitti by Exotic Veda: Detoxify, Purify, and Brighten Oily Skin',
        description: 'Naturally cleanse and refresh your skin with our Multani Mitti Powder. It helps absorb excess oil, reduce acne, and brighten your complexion.',
        updateInfo: 'Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/multani-mitti-powder-fullers-earth-clay?_pos=9&_sid=5edfdd030&_ss=r',
        route: '/products/multani-mitti',
        price: "$7",
        categories: ['Skin',],
    },
    {
        id: 7,
        link: '/products/sandalwood-powder',
        img: "/assets/Assets/sabdalwood/sandalwood Fornt.png ",
        title: 'Pure Sandalwood Powder  Refresh,  Nourish Your Skin Naturally',
        description: ' Elevate your skincare with our pure Sandalwood Powder, known for its soothing properties, reducing blemishes, and enhancing your skin’s natural radiance.',
        updateInfo: ' Click here to Learn Our  Tips  ',
        buyLink: 'https://revaais.com/products/exotic-veda-sandalwood-powder?_pos=6&_sid=5edfdd030&_ss=r',
        route: '/products/sandalwood-powder',
        price: "$7.90",
        categories: ['Skin',],
    },
    {
        id: 12,
        link: '/products/Lemongrass',
        img: '/assets/Assets/Lemongrass/lemonfront.jpg',
        title: 'Lemongrass Powder: Natural Boost for Digestive Health & Wellness',
        description: 'Support your health with our Jamun Seed Powder. Known for its antioxidant properties, it helps manage blood sugar levels and boosts digestion',
        updateInfo: 'Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/exotic-veda-jamun-seed-powder-eugenia-jambolana-black-plum-syzygium-cumini-100-grams?_pos=8&_sid=5edfdd030&_ss=r',
        route: '/products/jaamun-seed',
        price: "$4.99",
        categories: ['Hair', 'Skin', 'Diet', 'Wellness'],
    },
    {
        id: 8,
        link: '/products/beetroot-powder',
        img: "/assets/Assets/beetroot/beetroot  powder  front.png",
        title: 'Beetroot Powder: Delicious Superfood for Glowing Skin & Diet Support',
        description: ' Beetroot Powder enhances skin health and vitality. Rich in antioxidants, it supports a healthy diet, boosts energy, and promotes natural glow.',
        updateInfo: 'Click here to Learn Our  Tips ',
        buyLink: 'https://www.revaais.shop/products/exotic-veda-beetroot-powder-vegan-gluten-free-100-natural-non-gmo-100g',
        route: '/products/beetroot-powder',
        price: "$6.99",
        categories: ['Hair', 'Skin', 'Diet'],
    },
    {
        id: 9,
        link: '/products/alum-bar',
        img: '/assets/Assets/Alumbar/Alumbarss.jpg',
        title: 'Alum Bar Powder   Minimize Pores and Soothe Skin Naturally',
        description: 'Experience natural freshness with our Alum Bar, perfect for tightening pores, soothing skin, and acting as a gentle, chemical-free deodorant.',
        updateInfo: ' Click here to Learn Our  Tips  ',
        buyLink: 'https://revaais.com/products/revaais-pure-alum-block-for-shaving?_pos=1&_sid=30940bafe&_ss=r?variant=48956892152129',
        route: '/products/alum-bar',
        price: "$7.50",
        categories: ['Skin'],
    },
    {
        id: 10,
        link: '/products/moringa-leaf-powder',
        img: '/assets/Assets/Moringa/Moringa Leaf  (1).png',
        title: 'Moringa Leaf Powder   Natural Detox and Wellness Support for Vibrant Health',
        description: 'Supercharge your health with our Moringa Leaf Powder. Packed with vitamins and minerals, it boosts energy, supports immunity, and enhances overall wellness.',
        updateInfo: 'Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/exotic-veda-moringa-leaf-powder-moringa-oleifera-vegan-100-natural-non-gmo-100g?_pos=2&_sid=5edfdd030&_ss=r',
        route: '/products/moringa-leaf-powder',
        price: "$6.99",
        categories: ['Hair', 'Skin', 'Diet', 'Wellness'],
    },
    {
        id: 11,
        link: '/products/triphala-powder',
        img: '/assets/Assets/triphala/Tripahal 2 copy.png',
        title: 'Triphala Powder   Natural Detox and Wellness Support for Vibrant Health',
        description: 'Revitalize your health with our Triphala Powder, a traditional blend of three powerful fruits. It supports digestion, detoxifies the body, and promotes overall wellness.',
        updateInfo: 'Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/organic-triphala-powder?_pos=20&_sid=5edfdd030&_ss=r',
        route: '/products/triphala-powder',
        price: "$7.50",
        categories: ['Diet', 'Wellness'],
    },
    {
        id: 12,
        link: '/products/jaamun-seed',
        img: '/assets/Assets/jamunseed/jamunf.jpg',
        title: 'jamun Seed Powder   Promote Wellness with Natural Antioxidants and Nutrients',
        description: 'Support your health with our Jamun Seed Powder. Known for its antioxidant properties, it helps manage blood sugar levels and boosts digestion',
        updateInfo: 'Click here to Learn Our  Tips ',
        buyLink: 'https://revaais.com/products/exotic-veda-jamun-seed-powder-eugenia-jambolana-black-plum-syzygium-cumini-100-grams?_pos=8&_sid=5edfdd030&_ss=r',
        route: '/products/jaamun-seed',
        price: "$9.99",
        categories: ['Diet', 'Wellness'],
    },



];
